### PR TITLE
Add higher-resolution notification images

### PR DESCRIPTION
**Pull request by mbranch**
This might just be personal preference, but the previous `success`/`failed`/`pending` images were pretty low-resolution and rendered poorly on HiDPI displays. This pull request replaces the images with these simpler versions. 

I'm making a big assumption about whether all clients will intelligently down-sample the image, because my testing was limited. 

- Only tested with Growl (2.1.3) notifications on Mac.
- Source (Adobe Illustrator) file for these icons is here: https://www.dropbox.com/s/316eu7hpi45rx8a/notiffany.ai?dl=0

### CODE REVIEW

**Comment by e2** [comment]
I personally don't use GUI notifications, so I don't mind myself - but some people may prefer the fancy 3D effects of the originals. (Just saying).

I'm not a designer by any stretch, though.

Other than that, they scale properly on libnotify, while rb-notifu doesn't support images, so I see no issue with making these the default.

You might want to consider SVG as long as Growl supports it properly (no problem with libnotify on Linux).

If not, you may want to optimize the images - given how simple they are, they should take no more than ~2kb each (2-color palette, max opt, pngcrunch, etc.).

**Comment by mbranch** [comment]
Good call on optimizing the images, there were lots of savings to be had. I imagine sticking with .png will be the least problematic file type in the long term.

```
$ ls -lh
1.6K Feb 16 17:07 failed.png
1.6K Feb 16 17:07 pending.png
1.1K Feb 16 17:07 success.png
```

**Comment by e2** [comment]
Could you rebase/squash these 2 into a single commit?

**Comment by mbranch** [comment]
Sure! It's squashed now.

**Pull request merged**
