### PR TITLE
Better Emacs notifier

### PR DESCRIPTION
**Pull request by seanhagen**
Wrote some elisp that does a few things:

In `Notiffany::Notifier::Emacs::Client#initialize`, runs some elisp to
define a function ( but only if it isn't already defined ). This
function takes two arguments: `color`, and `bgcolor`. The function
that's defined does a few extra things:

1. it records the current foreground and background colours of the
mode-line face
2. it sets the mode-line face to what was passed in
3. it sets a timeout to reset the mode-line face back to what it was originally

In the actual `notify` call, it runs the function that was defined in
`initialize` in order to set the mode-line colors.

I don't mind Notiffany setting my mode-line too much, but I do like it to get set back to what it was after a short period of time. This way, users can also define their own Emacs function that will get called so that they can do something else when they get a notification.

I know that the big block of elisp in the class is kind of ugly, but it's one of the first functions I've written in elisp so I'm not sure if there's a more succinct way of putting it.

Also not sure if I'm using `available?` properly.

All the Emacs tests seem to still be passing, huzzah!

Let me know if there's stuff that needs fixing/tweaking/removing.

### CODE REVIEW

**Comment by e2** [comment]
While I'm not an emacs user to test this, I don't get the change at all:
1. 'elisp' is just a string variable set to a heredoc literal - it's not an accessor or anything
2. also, since it's a local variable with a string - there's not point in setting it inside the available block
3. tests work because this doesn't change anything

If at all, you should change the tests first to make them fail (TDD/BDD) - to make sure eval is called with your changes.

OTOH, I think the idea is a good one - about having a custom function.

I'd do the following:

Instead of 'notiffany-notify'  in the notify() method, make it a configurable parameter (so people can choose their own function - I don't know if there's a way to setup a default set of emacssclient list functions in home or something). 

Look at how the `:client` option is implemented - you could add a `:elisp_method` option and make it default to `notiffany-notify` - and implement the default so it calls set-face-attribute with the bg and fg colors.

In fact, start with the tests and create a block like: https://github.com/guard/notiffany/blob/master/spec/lib/notiffany/notifier/emacs_spec.rb#L85
but for the "custom elisp function" option (called 'notiffany-notify' or whatever you want to call it).

You'll probably want to test these cases:
1. Notifier - without options (if default function is passed to client)
2. Notifier - with custom function passed to Emacs::initialize() (if it's passed to client correctly)
3. Notifier - with custom function override passed to notify()
4. Client - whether it correctly called Sheller with the right code (without a custom function name)
5. Client - whether it correctly called Sheller with the right code (with a custom function name)

The stuff may be a bit tricky in Notiffany, so don't hesitate to ask if you're unsure.

**Comment by seanhagen** [comment]
Alrighty! Thanks for the feedback -- I'll make those changes.

**Comment by jpace** [comment]
I'd very much like to second this suggestion. As an Emacs user, I'd like the mode line to change only temporarily, such as for a few seconds, and then to revert to its previous settings.

**Comment by e2** [comment]
@jpace - I agree -  a configurable timeout is already what the TMux notifier has (and almost every other notifier). That's why the above function should use use the `:timeout` option - 10 sec for a fadeout may be too long.

**Comment by seanhagen** [comment]
I've been swamped at work over the past month. Things are getting better though -- I'm hoping to dive into making the above changes in the next week or so.

**Comment by cdlm** [comment]
:+1:

**Comment by rye** [comment]
I'd like to bump this PR&mdash;a better Emacs notifier is exactly what I've been wanting for a very long time.  Is there anything I can do to help test?

**Comment by e2** [comment]
Moved here: https://github.com/guard/notiffany/pull/20

**Pull request closed without merging**
